services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quiker
      POSTGRES_PASSWORD: quiker123
      POSTGRES_DB: quiker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - quiker-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - quiker-network

networks:
  quiker-network:
    driver: bridge

volumes:
  postgres_data:
